name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            cd /www/wwwroot/
            echo "Pull latest code..."
            git pull origin main
            echo "Install composer dependencies..."
            composer install --no-dev --no-interaction --prefer-dist
            echo "Run migrations..."
            php artisan migrate --force
            echo "Restart PHP-FPM..."
            sudo systemctl restart php-fpm
            echo "Deployment finished."
          EOF